name: Cargo&Despido

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3

      - name: Set up Python
        uses: actions/setup-python@v3  # Updated to v3
        with:
          python-version: '3.x'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller  # Install PyInstaller

      - name: Build executable with PyInstaller
        run: |
          python app/build_executable.py  # Run the build script

      - name: Archive the executable and static files
        run: |
          mkdir -p artifacts
          mv dist/chargefire artifacts/  # Move executable to artifacts folder
          cp -r app/static artifacts/static  # Copy static folder

      - name: Run the executable and test
        run: |
          ./artifacts/chargefire &  # Run executable in background
          sleep 10  # Wait for app to start
          curl http://127.0.0.1:5000/  # Check if app responds

      - name: Upload executable and static files as artifact
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: app-executable-and-static
          path: artifacts/  # Upload everything in artifacts folder